name: CI
on: [ push ]
jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: build
        run: ./gradlew core:build
      - name: terraform qat init, validate, apply
        if: github.ref != 'refs/heads/main'
        run: |
          cd core-terraform/terraform
          terraform init -backend-config=conf/qat.conf
          terraform validate
          terraform apply -auto-approve -var-file=environment/qat.tfvars
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: terraform dev init, validate, apply
        if: github.ref != 'refs/heads/main'
        run: |
          cd core-terraform/terraform
          terraform init -backend-config=conf/dev.conf -reconfigure
          terraform validate
          terraform apply -auto-approve -var-file=environment/dev.tfvars
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

