name: CI
on: [ push ]
jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
#      - name: Build Core
#        run: ./gradlew core:build
      - name: Terraform init, validate, apply
        run: |
          cd core-terraform/terraform
          terraform init
          terraform validate
          terraform apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

